export default{
  BUTTON_TYPE_BUYER_PAY:10, //  付款
  BUTTON_TYPE_BUYER_UNPAY_CANCEL: 11, //  未付款取消订单
  BUTTON_TYPE_BUYER_DIRECT_REFUND: 12, // 直接退单
  BUTTON_TYPE_BUYER_CONFIRM_SELF_TAKE: 13, //  确认自提
  BUTTON_TYPE_BUYER_CONFIRM_RECEIPT: 14, //  确认收货
  BUTTON_TYPE_BUYER_APPLY_REFUND: 15, //  申请退款
  BUTTON_TYPE_BUYER_VIEW_SALE: 16, //  查看退款服务单
  BUTTON_TYPE_BUYER_ORDER_DELETE: 17,  //  订单删除
  BUTTON_TYPE_BUYER_ORDER_AFTER_SALE: 18, // 申请售后
  BUTTON_TYPE_BUYER_ORDER_AFTER_SALE_IN_LIST_TO_DETAIL: 19, // 列表跳转售后详情
  BUTTON_TYPE_BUYER_ORDER_AFTER_SALE_UNDO: 20,  // 撤销申请
  BUTTON_TYPE_BUYER_ORDER_AFTER_SALE_EDIT: 21,  // 修改申请
  BUTTON_TYPE_BUYER_CONFIRM_ORDER: 25, // 确认金额
  BUTTON_TYPE_BUYER_PERIOD_ORDER_PAY: 26, // 账期支付
  BUTTON_TYPE_BUYER_PERIOD_CANCEL: 27, // 取消订单
  BUTTON_TYPE_BUYER_PERIOD_WAIT_PAY: 28, // 账期去付
  //金融
  BUTTON_TYPE_BUYER_FINANCIAL_DETAIL: 29, //查看金融详情
  BUTTON_TYPE_BUYER_FINANCIAL_CANCEL: 300, //取消金融
  BUTTON_TYPE_SELLER_AUDIT: 200 //卖家金融详情审核
}